# .github/workflows/release.yml

on:
  workflow_dispatch:

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            archive: zip
            suffix: ".exe"
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive: tar.gz tar.xz tar.zst
            suffix: ""
          - target: x86_64-apple-darwin
            os: macos-latest
            archive: zip
            suffix: ""
    runs-on: ${{ matrix.os }} 
    defaults:
      run:
        working-directory: bin
    steps:
      - uses: actions/checkout@v3
      - name: Build binary for production
        run: cargo build --release --target ${{ matrix.target }}
        
      - uses: actions/upload-artifact@v3
        with:
          name: planetary-${{ matrix.target }}${{ matrix.suffix }}
          path: bin/target/${{ matrix.target }}/release/planetary${{ matrix.suffix }}
      
