# .github/workflows/release.yml

on:
  workflow_dispatch:

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            suffix: ".exe"
            archive_suffix: ".zip"
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            suffix: ""
            archive_suffix: ".tar.gz"
          - target: x86_64-apple-darwin
            os: macos-latest
            suffix: ""
            archive_suffix: ".tar.gz"
    runs-on: ${{ matrix.os }} 
    defaults:
      run:
        working-directory: bin
    steps:
      - uses: actions/checkout@v3
      - name: Build binary for production
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Move binary to root
        run: mv target/${{ matrix.target }}/release/planetary${{ matrix.suffix }} planetary${{ matrix.suffix }}
      
      - name: Generate archive (unix)
        if: matrix.target != 'x86_64-pc-windows-gnu'
        run: tar -czvf planetary-${{ matrix.target }}.tar.gz planetary${{ matrix.suffix }}
    
      - name: Generate archive (windows)
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: Compress-Archive planetary${{ matrix.suffix }} planetary-${{ matrix.target }}.zip 
      
      - uses: actions/upload-artifact@v3
        with:
          name: planetary-${{ matrix.target }}${{ matrix.archive_suffix }}
          path: bin/planetary-${{ matrix.target }}${{ matrix.archive_suffix }}
      
