# .github/workflows/release.yml

on:
  workflow_dispatch:

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            suffix: ""
          - target: x86_64-apple-darwin
            os: macos-latest
            suffix: ""
    runs-on: ${{ matrix.os }} 
    defaults:
      run:
        working-directory: bin
    steps:
      - uses: actions/checkout@v3
      - name: Build binary for production
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Zipping up binary
        run: tar -czvf planetary-${{ matrix.target }}.tar.gz target/${{ matrix.target }}/release/planetary${{ matrix.suffix }}
        
      - uses: actions/upload-artifact@v3
        with:
          name: planetary-${{ matrix.target }}.tar.gz
          path: bin/planetary-${{ matrix.target }}.tar.gz
      
